# Generated by Django 6.0.3 on 2026-03-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_description_event_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
