# Generated by Django 6.0.3 on 2026-03-27 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_fooddonation_assigned_ngo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddonation',
            name='assigned_ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ngo'),
        ),
    ]
