# Generated by Django 6.0.3 on 2026-03-29 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fooddonation_latitude_fooddonation_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddonation',
            name='title',
        ),
    ]
