# Generated by Django 6.0.2 on 2026-04-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_fooddonation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donations/'),
        ),
    ]
